// JS fallback for blog posts data. Useful when viewing over file:// where fetch may be blocked.
window.BIM_POSTS = {
  posts: [
    {
      title: "BIM Is Not Just 3D — Why BIM Management Matters",
      title_en: "BIM Is Not Just 3D — Why BIM Management Matters",
      title_he: "BIM הוא לא רק תלת־ממד — למה ניהול BIM חשוב",
      date: "2025-09-25",
      excerpt: "BIM isn’t only 3D geometry — it’s managed information. Why BIM management matters and how automation roots it deeper.",
      excerpt_en: "BIM isn’t only 3D geometry — it’s managed information. Why BIM management matters and how automation roots it deeper.",
      excerpt_he: "BIM הוא לא רק גיאומטריה; זה מידע מנוהל. למה ניהול BIM חשוב ואיך אוטומציה מעמיקה אותו.",
      tags: ["BIM", "Management", "Automation", "Tekla"],
      tags_he: ["BIM", "ניהול", "אוטומציה", "Tekla"],
      thumbnail: "../images/future-roadmap-background.jpg",
      url: "posts/2025-09-25-bim-not-just-3d.html",
      readTime: "6 min read",
      readTime_en: "6 min read",
      readTime_he: "קריאה של 6 דק׳"
    },
    {
      title: "Fabrication Folder — Turning Modeling into Reality",
      title_en: "Fabrication Folder — Turning Modeling into Reality",
      title_he: "תיק הייצור — להפוך מודל למציאות",
      date: "2025-09-24",
      excerpt: "What goes into a complete fabrication folder and how to issue it right: phases, reports, drawings, DSTV/DXF, IFC, checks, and smart locking.",
      excerpt_en: "What goes into a complete fabrication folder and how to issue it right: phases, reports, drawings, DSTV/DXF, IFC, checks, and smart locking.",
      excerpt_he: "מה נכנס לתיקיית פבריקציה מלאה ואיך מנפיקים אותה נכון: פייזים, דוחות, שרטוטים, DSTV/DXF, IFC, בדיקות ונעילות חכמות.",
      tags: ["Fabrication", "Tekla", "Workflow", "Quality"],
      tags_he: ["פבריקציה", "Tekla", "תהליך", "איכות"],
      thumbnail: "../images/plugin-background.jpg",
      url: "posts/2025-09-24-fabrication-folder.html",
      readTime: "6 min read",
      readTime_en: "6 min read",
      readTime_he: "קריאה של 6 דק׳"
    },
    {
      title: "Custom Components in Tekla — Build Once, Reuse Everywhere",
      title_en: "Custom Components in Tekla — Build Once, Reuse Everywhere",
      title_he: "קומפוננטים ב‑Tekla — בונים פעם וממחזרים",
      date: "2025-09-23",
      excerpt: "Why custom components are essential for accurate, consistent, and future‑proof Tekla models — plus practical tips.",
      excerpt_en: "Why custom components are essential for accurate, consistent, and future‑proof Tekla models — plus practical tips.",
      excerpt_he: "למה קומפוננטים מותאמים חשובים למודל Tekla מדויק, עקבי ועתידי — עם טיפים מעשיים.",
      tags: ["Tekla", "Components", "BIM", "Productivity"],
      tags_he: ["Tekla", "קומפוננטים", "BIM", "פרודוקטיביות"],
      thumbnail: "../images/plugin-background.jpg",
      url: "posts/2025-09-23-custom-components-in-tekla.html",
      readTime: "6 min read",
      readTime_en: "6 min read",
      readTime_he: "קריאה של 6 דק׳"
    },
    {
      title: "Similar Parts — Why Accuracy Matters in Numbering",
      title_en: "Similar Parts — Why Accuracy Matters in Numbering",
      title_he: "חלקים דומים — למה הדיוק חשוב במספור",
      date: "2025-09-22",
      excerpt: "How precise modeling keeps parts sharing the same position number, saving time in drawings, fabrication, and erection.",
      excerpt_en: "How precise modeling keeps parts sharing the same position number, saving time in drawings, fabrication, and erection.",
      excerpt_he: "איך דיוק במידול מבטיח שחלקים יקבלו אותו מספר מיקום, וחוסך זמן בשרטוטים, בייצור ובהרכבה.",
      tags: ["Tekla", "BIM", "Quality", "Productivity"],
      tags_he: ["Tekla", "BIM", "איכות", "פרודוקטיביות"],
      thumbnail: "../images/future-roadmap-background.jpg",
      url: "posts/2025-09-22-similar-parts-numbering-accuracy.html",
  readTime: "6 min read",
  readTime_en: "6 min read",
  readTime_he: "קריאה של 6 דק׳"
    },
    {
      title: "Stop Rebuilding Settings — Tekla Firm Folder Basics",
      title_en: "Stop Rebuilding Settings — Tekla Firm Folder Basics",
      title_he: "מסיימים לבנות הכול מחדש — תיקיית Firm ב‑Tekla",
      date: "2025-09-21",
      excerpt: "Centralize attributes once in a Tekla firm folder so every new project starts ready to go.",
      excerpt_en: "Centralize attributes once in a Tekla firm folder so every new project starts ready to go.",
      excerpt_he: "מרכזים את המאפיינים בתיקיית Firm אחת כדי שכל פרויקט חדש יתחיל מוכן.",
      tags: ["Tekla", "Standards", "BIM", "Productivity"],
      tags_he: ["Tekla", "סטנדרטים", "BIM", "פרודוקטיביות"],
      thumbnail: "../images/future-roadmap-background.jpg",
      url: "posts/2025-09-21-tekla-firm-folder.html",
      readTime: "5 min read",
      readTime_en: "5 min read",
      readTime_he: "קריאה של 5 דק׳"
    },
    {
      title: "Symmetrical Railings — Importance in Detailing",
      title_en: "Symmetrical Railings — Importance in Detailing",
      title_he: "מעקות סימטריים — חשיבות בתכנון",
      date: "2023-11-20",
      excerpt: "Why symmetry in railing detailing saves time and reduces complexity in fabrication and installation.",
      excerpt_en: "Why symmetry in railing detailing saves time and reduces complexity in fabrication and installation.",
      excerpt_he: "מדוע סימטריה בתכנון מעקות חוסכת זמן ומפחיתה מורכבות בייצור ובהרכבה.",
      tags: ["Fabrication", "Tekla", "BIM"],
      tags_he: ["פבריקציה", "Tekla", "BIM"],
      thumbnail: "pics/SymmetricRailingIntro.jpg",
      url: "posts/2023-11-20-symmetrical-railings.html",
      readTime: "4 min read",
      readTime_en: "4 min read",
      readTime_he: "קריאה של 4 דק׳"
    },
    {
      title: "Automatically Dimensioning Assembly Drawings",
      title_en: "Automatically Dimensioning Assembly Drawings",
      title_he: "מידול אוטומטי של מידות שרטוטי הרכבה",
      date: "2023-11-30",
      excerpt: "Use Tekla's built-in dimensioning rules to automate assembly drawing dimensioning and reduce errors.",
      excerpt_en: "Use Tekla's built-in dimensioning rules to automate assembly drawing dimensioning and reduce errors.",
      excerpt_he: "השתמשו בכללי המידות המובנים של Tekla כדי לאוטומט מידות בשרטוטי הרכבה ולהפחית טעויות.",
      tags: ["Tekla", "Automation", "BIM"],
      tags_he: ["Tekla", "אוטומציה", "BIM"],
      thumbnail: "pics/assem_drawing_props.jpg",
      url: "posts/2023-11-30-automatically-dimensioning-assemblies.html",
      readTime: "6 min read",
      readTime_en: "6 min read",
      readTime_he: "קריאה של 6 דק׳"
    },
    {
      title: "Welcome to BIMblog",
      title_en: "Welcome to BIMblog",
      title_he: "ברוכים הבאים לבימבלוג",
      date: "2025-09-14",
      excerpt: "Kickoff: why fabrication, Tekla Structures, and automation matter for real project outcomes.",
      excerpt_en: "Kickoff: why fabrication, Tekla Structures, and automation matter for real project outcomes.",
      excerpt_he: "פתיחה: למה פבריקציה, Tekla Structures ואוטומציה חשובים לתוצאות בפרויקטים אמיתיים.",
      tags: ["Fabrication", "Tekla", "Automation", "BIM"],
      tags_he: ["פבריקציה", "Tekla", "אוטומציה", "BIM"],
      thumbnail: "../images/play-placeholder.jpg",
      url: "posts/2025-09-14-welcome.html",
      readTime: "3 min read",
      readTime_en: "3 min read",
      readTime_he: "קריאה של 3 דק׳"
    }
  ]
};
